name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml

      - name: Activate conda environment
        run: conda activate environment.yml

      - name: Run tests
        run: python your_code.py --inversion path/to/inversion --prompt "your prompt" --task_name cat2dog --results_folder output/test_cat --num_ddim_steps 50 --model_path CompVis/stable-diffusion-v1-4 --xa_guidance 0.1 --negative_guidance_scale 5.0 --use_float_16
